name: Run Script Every Minute

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run script with retry
        run: |
          for i in 1 2 3
          do
            echo "Attempt $i..."
            node index.js && break
            echo "Failed. Retrying in 10s..."
            sleep 10
          done
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
